### ISSUE TITLE
CH375USBPrinter.sendData missing?

### ISSUE THREAD

**Issue by nazmibojan** [gianluca-nitti/CH375-Arduino#1]
Hi Gianluca,
I just read your code and want to implement this code for ESP32. But in file 'USBPrinter.ino' row 69 there is a function called:
`printer.sendData(dataToPrint, len)`
I can't find this function in 'CH375USBPrinter.cpp'. I haven't test your code in Arduino before.
Thank you.

Regards,
Nazmi

**Comment by gianluca-nitti** [comment]
Hello, yes you are right, basically a previous version of the library code had the `sendData` function to transfer an array, but [later](https://github.com/gianluca-nitti/CH375-Arduino/commit/4a9a27f4036b011e579a171491c0b52186989fa1#diff-20998b43bf6ef1140126c9ae630152d0L56) an internal buffer managed by the `CH375USBPrinter` class was added and the class API changed and I forgot to update the example.
The function you need is `CH375USBPrinter::write(uint8_t b)`, which writes just one byte - I know, it's a terrible API, sorry for that. To fix the example you have to remove the whole if block starting on line 69 and  use a for loop, like this:
```
for (int i = 0; i < len; i++) {
  printer.write(dataToPrint[i]);
}
```
or, to get some feedback/debug info:
```
bool success = true;
for (int i = 0; i < len; i++) {
  if(!printer.write(dataToPrint[i])) {
    Serial.println("Failed to send data to the printer");
    success = false;
    break;
  }
}
if(success) {
  Serial.println("Succesfully printed!");
}
```
Unfortunately I can't test right now since I no longer have all the necessary hardware, however I tested that the example now compiles (I'll update it in the repository ASAP).
